/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugasAkhir;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Ahsin Fauzi
 */
public class input extends javax.swing.JFrame {
        Statement stat;
        Connection conn;
        PreparedStatement pre;
        int angka = 1;

    /**
     * Creates new form input
     */
    public void insertData(String ka){
     // TAMBAH DATA KERETA API
        String hsl="";
        if(cmbnoka.getSelectedItem()=="ka_15"){
            hsl = "KA15-";
        }else if (cmbnoka.getSelectedItem()=="ka_16"){
            hsl = "KA16-";
        }else if (cmbnoka.getSelectedItem()=="ka_17"){
            hsl = "KA17-";
        }else if (cmbnoka.getSelectedItem()=="ka_62"){
            hsl = "KA62-";
        }else if (cmbnoka.getSelectedItem()=="ka_63"){
            hsl = "KA63-";
        }else if (cmbnoka.getSelectedItem()=="ka_64"){
            hsl = "KA64-";
        }else if (cmbnoka.getSelectedItem()=="ka_65"){
            hsl = "KA65-";
        }else if (cmbnoka.getSelectedItem()=="ka_102"){
            hsl = "KA102-";
        }else if (cmbnoka.getSelectedItem()=="ka_19"){
            hsl = "KA19-";
        }else if (cmbnoka.getSelectedItem()=="ka_20"){
            hsl = "KA20-";
        }else if (cmbnoka.getSelectedItem()=="ka_21"){
            hsl = "KA21-";
        }else if (cmbnoka.getSelectedItem()=="ka_23"){
            hsl = "KA23-";
        }else if (cmbnoka.getSelectedItem()=="ka_25"){
            hsl = "KA25-";
        }else if (cmbnoka.getSelectedItem()=="ka_26"){
            hsl = "KA26-";
        }else if (cmbnoka.getSelectedItem()=="ka_27"){
            hsl = "KA27-";
        }else if (cmbnoka.getSelectedItem()=="ka_29"){
            hsl = "KA29-";
        }else if (cmbnoka.getSelectedItem()=="ka_33"){
            hsl = "KA33-";
        }else{
            hsl = "KA120-";
        }
        
        if(cmbkelas.getSelectedItem()=="EKS"){
            hsl += "EKS";
        }else if (cmbkelas.getSelectedItem()=="BIS"){
            hsl += "BIS";
        }else{
            hsl += "EKO";
        }
        hsl += angka;
        String exp[] = cmbnoka.getSelectedItem().toString().split("ka_");
        String sql = "INSERT INTO "+ka+" values('"+hsl+"','"+cmbnoka.getSelectedItem()+"','"+txtnamaka.getText()+"','"+txtasal.getText()+"','"+txttujuan.getText()+"','"+cmbkelas.getSelectedItem()+"','"+txtjmlpnp.getText()+"')";
            try {
                //java.sql.PreparedStatement pst=conn.prepareStatement(sql);
                conn = (Connection) TugasAkhir.config();
                pre = conn.prepareStatement(sql);
                pre.execute();
                JOptionPane.showMessageDialog(this, "data berhasil ditambah");
                this.dispose();
            } catch (SQLException ex) {
                Logger.getLogger(input.class.getName()).log(Level.SEVERE, null, ex);
                angka++;
                insertData((String) cmbnoka.getSelectedItem());
            }
    }
    public input() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addData = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        close = new javax.swing.JLabel();
        header = new javax.swing.JLabel();
        cmbnoka = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtnamaka = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtasal = new javax.swing.JTextField();
        cmbkelas = new javax.swing.JComboBox();
        txttujuan = new javax.swing.JTextField();
        txtjmlpnp = new javax.swing.JTextField();
        btn_simpan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/close.png"))); // NOI18N
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(662, Short.MAX_VALUE)
                .addComponent(close)
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(close)
                .addGap(0, 7, Short.MAX_VALUE))
        );

        header.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        header.setText("Input Data Perjalanan KA");

        cmbnoka.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ka_15", "ka_16", "ka_17", "ka_62", "ka_63", "ka_64", "ka_65", "ka_102", "ka_19", "ka_20", "ka_21", "ka_23", "ka_25", "ka_26", "ka_27", "ka_29", "ka_33", "ka_120" }));
        cmbnoka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbnokaActionPerformed(evt);
            }
        });

        jLabel3.setText("No KA");

        jLabel4.setText("Nama KA");

        txtnamaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamakaActionPerformed(evt);
            }
        });

        jLabel5.setText("Asal");

        jLabel6.setText("Tujuan");

        jLabel7.setText("Kelas");

        jLabel8.setText("Jumlah Penumpang");

        cmbkelas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "EKS", "BIS", "EKO" }));
        cmbkelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbkelasActionPerformed(evt);
            }
        });

        btn_simpan.setText("Simpan");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addDataLayout = new javax.swing.GroupLayout(addData);
        addData.setLayout(addDataLayout);
        addDataLayout.setHorizontalGroup(
            addDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addDataLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(addDataLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(addDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addDataLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(txtjmlpnp, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addDataLayout.createSequentialGroup()
                        .addGroup(addDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(69, 69, 69)
                        .addGroup(addDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbkelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtasal, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbnoka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnamaka, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txttujuan, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addDataLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(addDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addDataLayout.createSequentialGroup()
                        .addComponent(header)
                        .addGap(241, 241, 241))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addDataLayout.createSequentialGroup()
                        .addComponent(btn_simpan)
                        .addGap(47, 47, 47))))
        );
        addDataLayout.setVerticalGroup(
            addDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addDataLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(header)
                .addGap(18, 18, 18)
                .addGroup(addDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbnoka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(addDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtnamaka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(addDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtasal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(addDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txttujuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(addDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(cmbkelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(addDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(txtjmlpnp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(btn_simpan)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(addData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        // TODO add your handling code here:
         insertData((String) cmbnoka.getSelectedItem());
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void txtnamakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamakaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamakaActionPerformed

    private void cmbkelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbkelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbkelasActionPerformed

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_closeMouseClicked

    private void cmbnokaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbnokaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cmbnokaActionPerformed

    // tambah data rangka atap
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(input.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(input.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(input.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(input.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new input().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addData;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JLabel close;
    private javax.swing.JComboBox cmbkelas;
    private javax.swing.JComboBox cmbnoka;
    private javax.swing.JLabel header;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtasal;
    private javax.swing.JTextField txtjmlpnp;
    private javax.swing.JTextField txtnamaka;
    private javax.swing.JTextField txttujuan;
    // End of variables declaration//GEN-END:variables
}
