/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugasAkhir;
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JPanel;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;

/**
 *
 * @author Ahsin Fauzi
 */
public class K_Data extends javax.swing.JFrame {
    private DefaultTableModel tabmode;
    Connection konek;
    Statement stat;
    ResultSet hasil;
    String sql,kode;
    Populasi p;
    
    int data_perjalanan=0;

    /**
     * Creates new form K_Data
     */
    public K_Data() {
        initComponents();
        //setIcon();
        //reset();
        tampil(); 
        //window loaded
        addWindowListener (new WindowAdapter(){
                public void windowOpened (WindowEvent e){
//                    data_perjalanan();
                }
        });
        //warna background jframe
        this.getContentPane().setBackground(new Color(0,0,0));
    }
    
    public K_Data(Populasi p) {
        this.p = p;
        System.out.println("Optimal Gerbong K data= "+p.getOptimalGerbong());
        initComponents();
        //setIcon();
        //reset();
        tampil(); 
        // window loaded
        addWindowListener (new WindowAdapter(){
                public void windowOpened (WindowEvent e){
//                    data_perjalanan();
                }
        });
        //warna background jframe
        this.getContentPane().setBackground(new Color(0,0,0));
    }

    public void tampil(){
        tabmode =  new DefaultTableModel ();
        
        tb_kelolaData.setModel(tabmode);
        tabmode.addColumn("Kode");
        tabmode.addColumn("No KA");
        tabmode.addColumn("Nama KA");
        tabmode.addColumn("Asal");
        tabmode.addColumn("Tujuan");
        tabmode.addColumn("Kelas");
        tabmode.addColumn("Jumlah Penumpang");
           String sql = "SELECT * FROM ka_15";
       tabmode.fireTableDataChanged();
       try{ 
            TugasAkhir koneksi = new TugasAkhir();
            koneksi.login();
            stat = koneksi.stm;
            hasil = stat.executeQuery(sql);
           while (hasil.next()){
               String Kode = hasil.getString("KODE");
               String No_Ka = hasil.getString("NO_KA");
               String Nama_Ka = hasil.getString("NAMA_KA");
               String Asal = hasil.getString("ASAL");
               String Tujuan = hasil.getString("TUJUAN");
               String Kelas = hasil.getString("KELAS");
               String Jumlah_Penumpang = hasil.getString("JUMLAH_PENUMPANG");
               String[]data={Kode, No_Ka, Nama_Ka, Asal, Tujuan, Kelas, Jumlah_Penumpang};
               tabmode.addRow(data);
           }
       }catch (Exception e){
            JOptionPane.showMessageDialog(null, e, "informasi", JOptionPane.INFORMATION_MESSAGE);
       }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        judultabel = new javax.swing.JLabel();
        sidepanel = new javax.swing.JPanel();
        K_DATA = new javax.swing.JLabel();
        btn_perjalananKA = new javax.swing.JButton();
        tabel = new javax.swing.JScrollPane();
        tb_kelolaData = new javax.swing.JTable();
        add = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        kategoriKA = new javax.swing.JComboBox();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        judultabel.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        judultabel.setText("Data Perjalanan Kereta Api");

        sidepanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        K_DATA.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        K_DATA.setText("Kelola Data");

        btn_perjalananKA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Data.png"))); // NOI18N
        btn_perjalananKA.setText("Perjalanan KA");
        btn_perjalananKA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_perjalananKAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sidepanelLayout = new javax.swing.GroupLayout(sidepanel);
        sidepanel.setLayout(sidepanelLayout);
        sidepanelLayout.setHorizontalGroup(
            sidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidepanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_perjalananKA)
                    .addComponent(K_DATA))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sidepanelLayout.setVerticalGroup(
            sidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidepanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(K_DATA)
                .addGap(43, 43, 43)
                .addComponent(btn_perjalananKA)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tb_kelolaData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Kode", "No KA", "Nama KA", "Asal", "Tujuan", "Kelas", "Jumlah Penumpang"
            }
        ));
        tabel.setViewportView(tb_kelolaData);
        if (tb_kelolaData.getColumnModel().getColumnCount() > 0) {
            tb_kelolaData.getColumnModel().getColumn(0).setHeaderValue("Kode");
            tb_kelolaData.getColumnModel().getColumn(1).setHeaderValue("No KA");
            tb_kelolaData.getColumnModel().getColumn(2).setHeaderValue("Nama KA");
            tb_kelolaData.getColumnModel().getColumn(3).setHeaderValue("Asal");
            tb_kelolaData.getColumnModel().getColumn(4).setHeaderValue("Tujuan");
            tb_kelolaData.getColumnModel().getColumn(5).setHeaderValue("Kelas");
            tb_kelolaData.getColumnModel().getColumn(6).setHeaderValue("Jumlah Penumpang");
        }

        add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/add.png"))); // NOI18N
        add.setText("Tambah Data");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/delete.png"))); // NOI18N
        delete.setText("Hapus Data");

        kategoriKA.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "KA 15", "KA 16", "KA 17", "KA 62", "KA 63", "KA 64", "KA 65", "KA 102", "KA 19", "KA 20", "KA 21", "KA 23", "KA 25", "KA 26", "KA 27", "KA 29", "KA 33", "KA 120" }));
        kategoriKA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kategoriKAActionPerformed(evt);
            }
        });

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/back.png"))); // NOI18N
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sidepanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tabel, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(add)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(delete))
                            .addComponent(kategoriKA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(judultabel)
                        .addGap(148, 148, 148))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidepanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92)
                .addComponent(judultabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add)
                    .addComponent(delete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kategoriKA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(tabel, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_perjalananKAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_perjalananKAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_perjalananKAActionPerformed
    
    // DATA SPESIFIKASI KA
    // data KA 15
    public void ka_15(){
      //L_RA.setVisible(true);
       //isi tabel rangka atap
      tabmode =  new DefaultTableModel ();
      tb_kelolaData.setModel(tabmode);
      tabmode.addColumn("Kode");
      tabmode.addColumn("No KA");
      tabmode.addColumn("Nama KA");
      tabmode.addColumn("Asal");
      tabmode.addColumn("Tujuan");
      tabmode.addColumn("Kelas");
      tabmode.addColumn("Jumlah Penumpang");
        tabmode.getDataVector().removeAllElements();
        tabmode.fireTableDataChanged();
        sql = "SELECT * FROM ka_15";
        try{
            hasil = stat.executeQuery(sql);
            while ((hasil.next())){
              Object [] obj = new Object[6]; 
              obj[0] = hasil.getString("KODE");
              obj[1] = hasil.getString("NO_KA");
              obj[2] = hasil.getString("NAMA_KA");
              obj[3] = hasil.getString("ASAL");
              obj[4] = hasil.getString("TUJUAN");
              obj[5] = hasil.getString("KELAS");
              obj[5] = hasil.getString("JUMLAH_PENUMPANG");
              tabmode.addRow(obj);  
            }           
        // mengubah cell tabel
        tb_kelolaData.getModel().addTableModelListener((TableModelEvent e) -> {
            
            if(e.getType()==(TableModelEvent.UPDATE)){
                int intColumn = e.getColumn();
                int intRows = e.getFirstRow();
                UpdateDataKa_15(intRows); // update
            }
            });
        }catch (Exception e){
            //JOptionPane.showMessageDialog("gagal menampilkan data rangka atap", stat);
            System.err.println("gagal menampilkan data ka 15" +e.getMessage());
        }
    }
    
    // Update data rangka atap
    private void UpdateDataKa_15(int intRows){
        String Kode     = tb_kelolaData.getValueAt(intRows, 0).toString();
        String No_Ka = tb_kelolaData.getValueAt(intRows, 1).toString();
        String Nama_Ka = tb_kelolaData.getValueAt(intRows, 2).toString();
        String Asal    = tb_kelolaData.getValueAt(intRows, 3).toString();
        String Tujuan   = tb_kelolaData.getValueAt(intRows, 4).toString();
        String Kelas    = tb_kelolaData.getValueAt(intRows, 5).toString();
        String Jumlah_Penumpang    = tb_kelolaData.getValueAt(intRows, 6).toString();
        
        try{
            String sql = "UPDATE ka_15 "+
                         "SET No_Ka = '"+No_Ka+"'"+
                         ", Nama_Ka ='"+Nama_Ka+"'"+
                         ", Asal ='"+Asal+"'"+
                         ", Tujuan ='"+Tujuan+"'"+
                         ", Kelas ='"+Kelas+"'"+
                         ", Jumlah_Penumpang ='"+Jumlah_Penumpang+"'"+
                         " WHERE Kode ='"+Kode+"'";
            stat.execute(sql);
            JOptionPane.showMessageDialog(this, "data berhasil diubah");
        }catch (Exception e){
            System.err.println("gagal mengubah data ka 15 " +e.getMessage());
            e.printStackTrace();
        }
    }
    
    private void kategoriKAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kategoriKAActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_kategoriKAActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        input ka = new input();
        ka.setVisible(true);
        
    }//GEN-LAST:event_addActionPerformed

     // button hapus rangka atap
    private void b_hapusDataMouseClicked(java.awt.event.MouseEvent evt) {                                         
        int p = JOptionPane.showConfirmDialog(null, "apakah data akan dihapus ?","", JOptionPane.YES_NO_OPTION);
        //if(atap.getSelectedIndex()==0){  
            if (true){
                try{
                int SelectedRowIndex = tb_kelolaData.getSelectedRow();
                kode = tb_kelolaData.getValueAt(SelectedRowIndex, 0).toString();
                    System.out.println(kode);
                tabmode.removeRow(SelectedRowIndex);
                sql = "DELETE FROM ka_15 WHERE Kode = '"+kode+"'";
                //stat = konek.prepareStatement(sql);
                stat.executeUpdate(sql);
                JOptionPane.showMessageDialog(this, "data berhasil dihapus");
                }catch (Exception e){
                    JOptionPane.showMessageDialog(this, "data gagal dihapus");
                }
            }        
//        }else{
//            if (true){
//                try{
//                int SelectedRowIndex = tb_kelolaData.getSelectedRow();
//
//                kode = tb_kelolaData.getValueAt(SelectedRowIndex, 0).toString();
//                    System.out.println(kode);
//                tabmode.removeRow(SelectedRowIndex);
//                sql = "DELETE FROM penutup_atap WHERE Kode = '"+kode+"'";
//                //stat = konek.prepareStatement(sql);
//                stat.executeUpdate(sql);
//                JOptionPane.showMessageDialog(this, "data berhasil dihapus");
//                }catch (Exception e){
//                    JOptionPane.showMessageDialog(this, "data gagal dihapus");
//                }
//            } 
//        }
    } 
    
    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        tampilanAwal back = new tampilanAwal(p);
        back.setVisible(true);
        dispose();
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(K_Data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(K_Data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(K_Data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(K_Data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new K_Data().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel K_DATA;
    private javax.swing.JButton add;
    private javax.swing.JButton back;
    private javax.swing.JButton btn_perjalananKA;
    private javax.swing.JButton delete;
    private javax.swing.JLabel judultabel;
    private javax.swing.JComboBox kategoriKA;
    private javax.swing.JPanel sidepanel;
    private javax.swing.JScrollPane tabel;
    public javax.swing.JTable tb_kelolaData;
    // End of variables declaration//GEN-END:variables
}
