/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugasAkhir;

import java.awt.Toolkit;
/**
 *
 * @author Ahsin Fauzi
 */
public class tampilanAwal extends javax.swing.JFrame {
    public static tampilanAwal back;
    Populasi p = new Populasi(100);
    public tampilanAwal() {
        
        initComponents();
        //iconGambar
        //setIcon();
        //tampilan fullscreen
        // fullscreen = Toolkit.getDefaultToolkit();
        //int xsize = (int)fullscreen.getScreenSize().getWidth();
        //int ysize = (int)fullscreen.getScreenSize().getWidth();
        //this.setSize(xsize, ysize);
    }
    public tampilanAwal(Populasi p){
        this.p = p;
        System.out.println("Optimal Gerbong = "+p.getOptimalGerbong());
        initComponents();
        //setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tampilanAwal = new javax.swing.JPanel();
        feed_menu = new javax.swing.JPanel();
        kelola_data = new javax.swing.JButton();
        keloladata = new javax.swing.JLabel();
        optimalisasi = new javax.swing.JButton();
        opt = new javax.swing.JLabel();
        detail_optimalisasi = new javax.swing.JButton();
        dt_opt = new javax.swing.JLabel();
        tentang_sistem = new javax.swing.JButton();
        ttg_sistem = new javax.swing.JLabel();
        bar_atas = new javax.swing.JPanel();
        close = new javax.swing.JLabel();
        logo_train = new javax.swing.JLabel();
        judul1 = new javax.swing.JLabel();
        judul2 = new javax.swing.JLabel();
        judul3 = new javax.swing.JLabel();
        P_Tentang = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        barAtas = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setUndecorated(true);

        feed_menu.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        kelola_data.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/KelolaData.png"))); // NOI18N
        kelola_data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kelola_dataActionPerformed(evt);
            }
        });

        keloladata.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        keloladata.setText("Kelola Data");

        optimalisasi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Optimalisasi.png"))); // NOI18N
        optimalisasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optimalisasiActionPerformed(evt);
            }
        });

        opt.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        opt.setText("Optimalisasi");

        detail_optimalisasi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/spesifik.png"))); // NOI18N

        dt_opt.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        dt_opt.setText("Detail Optimalisasi");

        tentang_sistem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/about.png"))); // NOI18N

        ttg_sistem.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        ttg_sistem.setText("Tentang Sistem");

        javax.swing.GroupLayout feed_menuLayout = new javax.swing.GroupLayout(feed_menu);
        feed_menu.setLayout(feed_menuLayout);
        feed_menuLayout.setHorizontalGroup(
            feed_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(feed_menuLayout.createSequentialGroup()
                .addGroup(feed_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(feed_menuLayout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(keloladata)
                        .addGap(136, 136, 136)
                        .addComponent(opt)
                        .addGap(118, 118, 118)
                        .addComponent(dt_opt)
                        .addGap(99, 99, 99)
                        .addComponent(ttg_sistem))
                    .addGroup(feed_menuLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(kelola_data)
                        .addGap(69, 69, 69)
                        .addComponent(optimalisasi)
                        .addGap(63, 63, 63)
                        .addComponent(detail_optimalisasi)
                        .addGap(63, 63, 63)
                        .addComponent(tentang_sistem)))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        feed_menuLayout.setVerticalGroup(
            feed_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(feed_menuLayout.createSequentialGroup()
                .addGroup(feed_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(optimalisasi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kelola_data, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(detail_optimalisasi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tentang_sistem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(feed_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dt_opt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(feed_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(keloladata)
                        .addComponent(opt)
                        .addComponent(ttg_sistem, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        bar_atas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.BOTTOM));

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/close.png"))); // NOI18N

        javax.swing.GroupLayout bar_atasLayout = new javax.swing.GroupLayout(bar_atas);
        bar_atas.setLayout(bar_atasLayout);
        bar_atasLayout.setHorizontalGroup(
            bar_atasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bar_atasLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(close))
        );
        bar_atasLayout.setVerticalGroup(
            bar_atasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(close, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        logo_train.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/trains.png"))); // NOI18N

        judul1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        judul1.setText("SISTEM OPTIMALISASI");

        judul2.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        judul2.setText("PENGGUNAAN GERBONG KELAS KERETA API PENUMPANG");

        judul3.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        judul3.setText("MENGGUNAKAN ALGORITMA GENETIKA");

        javax.swing.GroupLayout tampilanAwalLayout = new javax.swing.GroupLayout(tampilanAwal);
        tampilanAwal.setLayout(tampilanAwalLayout);
        tampilanAwalLayout.setHorizontalGroup(
            tampilanAwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tampilanAwalLayout.createSequentialGroup()
                .addGroup(tampilanAwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tampilanAwalLayout.createSequentialGroup()
                        .addGap(394, 394, 394)
                        .addComponent(logo_train))
                    .addGroup(tampilanAwalLayout.createSequentialGroup()
                        .addGap(345, 345, 345)
                        .addComponent(judul1))
                    .addGroup(tampilanAwalLayout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(judul2))
                    .addGroup(tampilanAwalLayout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addComponent(judul3)))
                .addContainerGap(158, Short.MAX_VALUE))
            .addComponent(bar_atas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(tampilanAwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(feed_menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tampilanAwalLayout.setVerticalGroup(
            tampilanAwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tampilanAwalLayout.createSequentialGroup()
                .addComponent(bar_atas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(logo_train, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1, 1, 1)
                .addComponent(judul1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(judul2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(judul3)
                .addGap(203, 203, 203))
            .addGroup(tampilanAwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(tampilanAwalLayout.createSequentialGroup()
                    .addGap(319, 319, 319)
                    .addComponent(feed_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jLabel1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        jLabel1.setText("Tentang Sistem");

        jLabel2.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        jLabel2.setText("Sistem ini dibangun untuk memberikan hasil optimalisasi");

        jLabel3.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        jLabel3.setText("penggunaan gerbong kelas kereta api");

        jLabel4.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        jLabel4.setText("berdasarkan jumlah penumpang dan jam keberangkatan.");

        jLabel5.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        jLabel5.setText("Manfaat dari penelitian ini diharapkan dapat ");

        jLabel6.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        jLabel6.setText("membantu perusahaan dalam menentukan penggunaan gerbong secara");

        jLabel7.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        jLabel7.setText("optimal sesuai dengan jadwal keberangkatan masing-masing kereta api");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/back.png"))); // NOI18N

        javax.swing.GroupLayout barAtasLayout = new javax.swing.GroupLayout(barAtas);
        barAtas.setLayout(barAtasLayout);
        barAtasLayout.setHorizontalGroup(
            barAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, barAtasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        barAtasLayout.setVerticalGroup(
            barAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, barAtasLayout.createSequentialGroup()
                .addGap(0, 13, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout P_TentangLayout = new javax.swing.GroupLayout(P_Tentang);
        P_Tentang.setLayout(P_TentangLayout);
        P_TentangLayout.setHorizontalGroup(
            P_TentangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(barAtas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(P_TentangLayout.createSequentialGroup()
                .addGroup(P_TentangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(P_TentangLayout.createSequentialGroup()
                        .addGap(289, 289, 289)
                        .addComponent(jLabel1))
                    .addGroup(P_TentangLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(P_TentangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))))
                .addContainerGap(291, Short.MAX_VALUE))
        );
        P_TentangLayout.setVerticalGroup(
            P_TentangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_TentangLayout.createSequentialGroup()
                .addComponent(barAtas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addContainerGap(200, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(P_Tentang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(tampilanAwal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(P_Tentang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(tampilanAwal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kelola_dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kelola_dataActionPerformed
        // memanggil halaman kelola data
        K_Data menuKData = new K_Data(p);
        menuKData.setVisible(true);
        dispose();
    }//GEN-LAST:event_kelola_dataActionPerformed
   
    private void optimalisasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optimalisasiActionPerformed
        // memanggil halaman optimalisasi
//        Optimalisasi menuOp = new Optimalisasi(p);
//        menuOp.setVisible(true);
//        dispose();
    }//GEN-LAST:event_optimalisasiActionPerformed

    private void detail_optimalisasiActionPerformed(java.awt.event.ActionEvent evt){
        // memanggil halaman detail optimalisasi
//        DetailOpt detOpt = new DetailOpt(p);
//        detOpt.insertKromosom(p);
//        detOpt.setVisible(true);
//        dispose();
    }
    
    private void tentang_sistemActionPerformed(java.awt.event.ActionEvent evt){
        // memanggil halaman tentang sistem
        P_Tentang.setVisible(true);
        tampilanAwal.setVisible(false);
        //P_Panduan.setVisible(false);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tampilanAwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tampilanAwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tampilanAwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tampilanAwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                back = new tampilanAwal();
                back.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel P_Tentang;
    private javax.swing.JPanel barAtas;
    private javax.swing.JPanel bar_atas;
    private javax.swing.JLabel close;
    private javax.swing.JButton detail_optimalisasi;
    private javax.swing.JLabel dt_opt;
    private javax.swing.JPanel feed_menu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel judul1;
    private javax.swing.JLabel judul2;
    private javax.swing.JLabel judul3;
    private javax.swing.JButton kelola_data;
    private javax.swing.JLabel keloladata;
    private javax.swing.JLabel logo_train;
    private javax.swing.JLabel opt;
    private javax.swing.JButton optimalisasi;
    private javax.swing.JPanel tampilanAwal;
    private javax.swing.JButton tentang_sistem;
    private javax.swing.JLabel ttg_sistem;
    // End of variables declaration//GEN-END:variables
}
